# Generated by Django 3.0 on 2020-11-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20201122_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_back',
            field=models.ImageField(null=True, upload_to='ProductImg'),
        ),
    ]
