# Generated by Django 3.0 on 2020-11-27 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_main_image_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image_back',
        ),
        migrations.CreateModel(
            name='ExtraImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='ProductImg')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='ProductImg')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='ProductImg')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='ProductImg')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='ProductImg')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_imgs', to='Store.Product')),
            ],
        ),
    ]
