# Generated by Django 3.0 on 2020-11-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20201126_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimgs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_imgs', to='Store.Product'),
        ),
    ]
