# Generated by Django 3.0 on 2020-12-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20201126_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=264)),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='By default Status is False. If you want to show this review in your web page then make it True.', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Store.Product')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
