# Generated by Django 3.0 on 2020-12-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20201205_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='status',
        ),
    ]
