# Generated by Django 3.0 on 2021-01-21 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='ShippingAddress',
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
