# Generated by Django 3.0 on 2021-02-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_paymentmethos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethos',
            new_name='PaymentMethod',
        ),
    ]
