# Generated by Django 3.0 on 2021-02-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_auto_20210213_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('COD', 'Cash On Delivary')], max_length=10),
        ),
    ]
