# Generated by Django 3.0 on 2021-02-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_auto_20210219_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='joined',
            new_name='created',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
