# Generated by Django 3.0 on 2021-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_auto_20210221_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('CARD', 'Card'), ('COD', 'Cash On Delivary'), ('SSLCOM', 'SSLCommerz')], max_length=10),
        ),
    ]
