# Generated by Django 3.0 on 2021-02-20 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20210217_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
