# Generated by Django 3.0 on 2021-02-21 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20210220_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentId',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='validId',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
