# Generated by Django 3.0 on 2021-02-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20210221_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ON HOLD', 'On hold'), ('RECEIVED', 'Received'), ('REPAREING', 'prepareing'), ('SHIPPING', 'Shipping'), ('CANCELLED', 'Cancelled')], default='ON HOLD', max_length=15, null=True),
        ),
    ]
