# Generated by Django 3.0 on 2021-02-21 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20210221_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentId',
            field=models.UUIDField(default=uuid.uuid1),
        ),
        migrations.AlterField(
            model_name='order',
            name='validId',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
