# Generated by Django 3.0 on 2021-02-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_auto_20210221_0955'),
        ('Order', '0013_auto_20210221_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_addredd',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.ShippingAddress'),
        ),
    ]
