# Generated by Django 3.0 on 2021-02-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_order_shipping_addredd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_addredd',
            new_name='shipping_address',
        ),
    ]
