# Generated by Django 3.0 on 2021-02-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_auto_20210221_1242'),
        ('Order', '0015_auto_20210221_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.ShippingAddress'),
        ),
    ]
